version: '3.8'

services:
  # 1. Entorno principal: Jupyter + PySpark + Selenium
  workspace:
    build: .
    container_name: BigData_workspace
    platform: linux/amd64
    ports:
      - "8888:8888"   # Jupyter Lab
      - "6080:6080"   # Visualizador VNC (scraping dinámico)
      - "5900:5900"   # Acceso VNC directo
      - "4040:4040"   # Spark UI
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=bigdata     # Mantenemos la seguridad de tu archivo
      - JUPYTER_ALLOW_INSECURE_WRITES=true
      - DISPLAY=:99
    shm_size: "2gb"
    dns:
      - 8.8.8.8
    user: root
    restart: always
    depends_on:
      - mongodb
      - admin-db
      - admin-db-atlas
    networks:
      - bigdata_net

  # 2. Base de Datos NoSQL local (MongoDB)
  mongodb:
    image: mongo:latest
    container_name: BigData_MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - bigdata_net

  # 3. Visualizador de MongoDB (Local)
  admin-db:
    image: mongo-express:latest
    container_name: BigData_Visualizer_Local
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    dns:
      - 8.8.8.8
    restart: always
    depends_on:
      - mongodb
    networks:
      - bigdata_net

  # 4. Visualizador de MongoDB (Atlas en la nube)
  admin-db-atlas:
    image: mongo-express:latest
    container_name: BigData_Visualizer_Atlas
    ports:
      - "8082:8081"
    environment:
      # Conexión configurada exactamente para tu clúster
      - ME_CONFIG_MONGODB_URL=mongodb+srv://BenjaminRamirez:[TU_PASSWORD_AQUI]@cluster0.kek1o3u.mongodb.net/Proyecto_Bigdata?retryWrites=true&w=majority
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    dns:
      - 8.8.8.8
    restart: always
    networks:
      - bigdata_net

volumes:
  mongo_data:

networks:
  bigdata_net:
    driver: bridge